version: "3.8"
services:
  generator:
    build: ./generator/
    restart: always
    ports:
      - "8000:8000"

  api:
    build: ./api/
    restart: always
    depends_on:
      - generator
    ports:
      - "8080:8080"

  frontend:
    build: ./front
    ports:
      - 80:80
    depends_on:
      - api
